pinecone:
  api_key: "${{PINECONE_API_KEY}}"
  index_name: "popqa-compression"


embeddings:
  model: "sentence-transformers/all-MiniLM-L6-v2"

compression:
  type: "llm_extraction"
  top_k: 5
  llm:
    provider: "groq"
    model: "llama-3.3-70b-versatile"
    api_key: "${GROQ_API_KEY}"

retrieval:
  top_k: 20

rag:
  enabled: false

logging:
  name: "pinecone_popqa_llm"
  level: "INFO"
